package main;

import java.awt.Color;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.event.CaretEvent;
import javax.swing.event.CaretListener;

public class HlavníOkno extends javax.swing.JFrame {

    final String ULOZENADATA = "data.bin";
    RodnéČíslo rc;
    ArrayList<Osoba> seznam = new ArrayList<>();
    int pozice = 0;

    /**
     * Creates new form HlavníOkno
     */
    public HlavníOkno() {
        initComponents();
        nactiDataZeSouboru();
        //seznam.add(new Osoba("René Hužva", new RodnéČíslo("966126/0356")));
        //seznam.add(new Osoba("Jane", new RodnéČíslo("966126/0357")));
        vyplnPolicka(pozice);
        jTextFieldRC.addCaretListener(new CaretListener() {
            @Override
            public void caretUpdate(CaretEvent e) {
                if (RodnéČíslo.isOk(jTextFieldRC.getText())) {
                    jTextFieldRC.setBackground(Color.white);
                } else {
                    jTextFieldRC.setBackground(Color.orange);
                }
            }
        });
    }

    private void zapisDataDoSouboru() {
        FileOutputStream vystup;
        ObjectOutputStream ovystup;
        try {
            vystup = new FileOutputStream(ULOZENADATA);
            ovystup = new ObjectOutputStream(vystup);
            // zapíšeme objekt do souboru
            ovystup.writeObject(seznam);
            ovystup.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void nactiDataZeSouboru() {
        FileInputStream vstup;
        ObjectInputStream ovstup;
        try {
            vstup = new FileInputStream(ULOZENADATA);
            ovstup = new ObjectInputStream(vstup);
            // načteme celý ArrayList jako jeden objekt ze souboru
            seznam = (ArrayList<Osoba>) ovstup.readObject();
            ovstup.close();
        } catch (FileNotFoundException ex) {
            System.out.println("Soubor s daty nenalezen.");
            //Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (java.io.EOFException ex) {
            Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(HlavníOkno.class.getName()).log(Level.SEVERE, null, ex);
        }
        //když je prázdný seznam, potřebujeme alespon jeden prvek
        if (seznam.size() < 1) {
            seznam.add(new Osoba("", new RodnéČíslo("")));
        }
    }

    private void vyplnPolicka(int i) {
        try {
            jTextFieldJmeno.setText(seznam.get(i).getJmeno());
            jTextFieldRC.setText(seznam.get(i).getRC());
        } catch (IndexOutOfBoundsException e) {
            // na požadované pozici (ještě) nic není
            jTextFieldJmeno.setText("");
            jTextFieldRC.setText("");
        }
        jLabelPozice.setText(Integer.toString(pozice) + "/" + (seznam.size() - 1));
    }

    private void ulozPolicka(int i) {
        if (i > seznam.size() - 1) {
            // přidáme další člen ArrayListu
            seznam.add(new Osoba(
                    jTextFieldJmeno.getText(),
                    new RodnéČíslo(jTextFieldRC.getText()))
            );
        } else {
            // přepíšeme (aktualizujeme) člen ArrayListu
            seznam.get(i).setJmeno(jTextFieldJmeno.getText());
            seznam.get(i).setRC(jTextFieldRC.getText());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldJmeno = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldRC = new javax.swing.JTextField();
        jButtonKontrola = new javax.swing.JButton();
        jButtonKonec = new javax.swing.JButton();
        jButtonPredchozi = new javax.swing.JButton();
        jButtonDalsi = new javax.swing.JButton();
        jLabelPozice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Rodné číslo");

        jLabel1.setText("Jméno:");

        jLabel2.setText("Rodné číslo:");

        jButtonKontrola.setText("Kontrola");
        jButtonKontrola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKontrolaActionPerformed(evt);
            }
        });

        jButtonKonec.setText("Konec");
        jButtonKonec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonKonecActionPerformed(evt);
            }
        });

        jButtonPredchozi.setText("Předchozí");
        jButtonPredchozi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPredchoziActionPerformed(evt);
            }
        });

        jButtonDalsi.setText("Další");
        jButtonDalsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDalsiActionPerformed(evt);
            }
        });

        jLabelPozice.setText("?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addComponent(jLabelPozice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonKontrola)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPredchozi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDalsi)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonKonec))
                    .addComponent(jTextFieldJmeno)
                    .addComponent(jTextFieldRC))
                .addContainerGap())
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButtonDalsi, jButtonKonec, jButtonKontrola, jButtonPredchozi});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldJmeno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldRC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonKontrola)
                    .addComponent(jButtonKonec)
                    .addComponent(jButtonPredchozi)
                    .addComponent(jButtonDalsi)
                    .addComponent(jLabelPozice))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonKonecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKonecActionPerformed
        ulozPolicka(pozice);
        zapisDataDoSouboru();
        System.exit(0);
    }//GEN-LAST:event_jButtonKonecActionPerformed

    private void jButtonKontrolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonKontrolaActionPerformed
        if (RodnéČíslo.isOk(jTextFieldRC.getText())) {
            JOptionPane.showMessageDialog(null, "Rodné číslo je v pořádku",
                    "Rodné číslo", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Chyba v rodném čísle",
                    "Rodné číslo", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonKontrolaActionPerformed

    private void jButtonPredchoziActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPredchoziActionPerformed
        ulozPolicka(pozice);
        // nepůjdeme před první člen
        if (pozice > 0) {
            pozice--;
        }
        vyplnPolicka(pozice);
    }//GEN-LAST:event_jButtonPredchoziActionPerformed

    private void jButtonDalsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDalsiActionPerformed
        int size = seznam.size();
        if (pozice < seznam.size() - 1) {
            ulozPolicka(pozice);
            pozice++;
        } else if (pozice == seznam.size() - 1 && !jTextFieldJmeno.getText().isEmpty()) {
            // další je když bylo něco vyplněno
            ulozPolicka(pozice);
            pozice++;
        }
        vyplnPolicka(pozice);
    }//GEN-LAST:event_jButtonDalsiActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HlavníOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HlavníOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HlavníOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HlavníOkno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HlavníOkno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDalsi;
    private javax.swing.JButton jButtonKonec;
    private javax.swing.JButton jButtonKontrola;
    private javax.swing.JButton jButtonPredchozi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelPozice;
    private javax.swing.JTextField jTextFieldJmeno;
    private javax.swing.JTextField jTextFieldRC;
    // End of variables declaration//GEN-END:variables
}
